### PR TITLE
Add [ Sebastian`s ] picture to the bitbee team section on the website

### PR DESCRIPTION
**Pull request by blowymind99**

### CODE REVIEW

**Review by marianzburlea — APPROVED** [review]
Perfectos

**Review by RalucaRbc — APPROVED** [review]
💯 Great Sebastian

**Comment by MariaTeo** [comment]
nice

**Comment by biggicode** [comment]
A nice comment

**Review by marianzburlea — APPROVED** [review]

**Review by andreimaff — APPROVED** [review]
good job

**Review by Constantin-Matei — APPROVED** [review]
Frumos :)

**Review by biggicode — APPROVED** [review]

**Pull request merged**
