### PR TITLE
Add [ Paul ] picture to the bitbee team section on the website

### LINKED ISSUE #20: Add [ Paul ] picture to the bitbee team section on the website

### PR DESCRIPTION
**Pull request by NicolaePaulGeambazu**
this closes #20

### CODE REVIEW

**Review by marianzburlea — APPROVED** [review]
💯

**Review by marianzburlea — APPROVED** [review]
👍

**Review by RalucaRbc — APPROVED** [review]
💯 Nice work Paul

**Review by BogdanNegura — APPROVED** [review]
👍

**Review by BogdanNegura — APPROVED** [review]

**Review by vasilemaftita — COMMENTED** [review]
Nice work

**Pull request merged**
